// This file was auto-generated by app/scripts/watch-assets.mjs and should not be edited manually.

export { default as IconIconsAuthApple } from "./icons/auth/apple.svg";
export { default as IconIconsAuthHeart } from "./icons/auth/heart.svg";
export { default as IconIconsAuthQq } from "./icons/auth/qq.svg";
export { default as IconIconsAuthWechat } from "./icons/auth/wechat.svg";
export { default as IconIconsHomeLayoutAlbum } from "./icons/home-layout/album.svg";
export { default as IconIconsHomeLayoutHome } from "./icons/home-layout/home.svg";
export { default as IconIconsHomeLayoutInteract } from "./icons/home-layout/interact.svg";
export { default as IconIconsHomeLayoutMine } from "./icons/home-layout/mine.svg";
export { default as IconIconsHomeDoubleHeart } from "./icons/home/double-heart.svg";
export { default as IconIconsHomeGift } from "./icons/home/gift.svg";
export { default as IconIconsHomeStatus } from "./icons/home/status.svg";
export const ImageImagesAuthBackground = require("./images/auth/auth-background.png");
export const ImageImagesAvatarFemale = require("./images/avatar-female.png");
export const ImageImagesAvatarMale = require("./images/avatar-male.png");
export const ImageImagesIcon = require("./images/icon.png");
export const ImageImagesSplash = require("./images/splash.png");
export const ImageImagesStatusPinkBear = require("./images/status/pink-bear.png");
