import { readdir, writeFile } from "node:fs/promises";
import { dirname, extname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const appRoot = dirname(__dirname);
const assetsDir = join(appRoot, "assets");
const outputFile = join(assetsDir, "index.ts");
const isWatchMode = process.argv.includes("--watch");

const watchList = [
  {
    dir: join(assetsDir, "icons"),
    exportPrefix: "",
    exportKind: "component",
    extensions: new Set([".svg"]),
  },
  {
    dir: join(assetsDir, "images"),
    exportPrefix: "",
    exportKind: "require",
    extensions: new Set([".png", ".jpg", ".jpeg", ".webp", ".gif", ".avif", ".bmp"]),
  },
  {
    dir: assetsDir,
    exportPrefix: "",
    exportKind: "require",
    extensions: new Set([".mp4"]),
  },
];
const watchedRoots = watchList.map((entry) => entry.dir);

let debounceTimer = null;

process.on("SIGINT", () => process.exit(0));
process.on("SIGTERM", () => process.exit(0));

await buildAssetsIndex();

if (isWatchMode) {
  const { watch } = await import("chokidar");
  const watcher = watch(watchedRoots, {
    ignored: outputFile,
    ignoreInitial: true,
  });

  watcher.on("add", scheduleBuild);
  watcher.on("change", scheduleBuild);
  watcher.on("unlink", scheduleBuild);
  watcher.on("addDir", scheduleBuild);
  watcher.on("unlinkDir", scheduleBuild);

  console.log(`${formatTime()} Watching asset changes...`);
}

async function buildAssetsIndex() {
  const assetFiles = await collectAssetFiles();
  const exportEntries = buildExportEntries(assetFiles);

  const lines = [
    "// This file was auto-generated by app/scripts/watch-assets.mjs and should not be edited manually.",
    "",
    ...exportEntries.map((entry) => entry.line),
    "",
  ];

  await writeFile(outputFile, lines.join("\n"), "utf8");
  console.log(`${formatTime()} Generated ${relative(appRoot, outputFile).replace(/\\/g, "/")}`);
}

function scheduleBuild() {
  if (debounceTimer) {
    clearTimeout(debounceTimer);
  }

  debounceTimer = setTimeout(() => {
    debounceTimer = null;
    void buildAssetsIndex();
  }, 200);
}

async function collectAssetFiles() {
  const files = [];
  
  for (const entry of watchList) {
    const entryFiles = await walkFiles(entry.dir);
    files.push(
      ...entryFiles
        .filter((filePath) => entry.extensions.has(extname(filePath).toLowerCase()))
        .map((filePath) => {
          const ext = extname(filePath).slice(1);

          return {
            filePath,
            exportKind: entry.exportKind,
            exportPrefix: entry.exportPrefix,
            extensionSuffix: ext.charAt(0).toUpperCase() + ext.slice(1),
          };
        }),
    );
  }

  return files
    .sort((a, b) =>
      a.filePath.localeCompare(b.filePath, "en", {
        sensitivity: "base",
        numeric: true,
      }),
    );
}

async function walkFiles(dir) {
  const entries = await readdir(dir, { withFileTypes: true });
  const files = [];

  for (const entry of entries) {
    const fullPath = join(dir, entry.name);

    if (entry.isDirectory()) {
      files.push(...(await walkFiles(fullPath)));
      continue;
    }

    if (entry.isFile()) {
      files.push(fullPath);
    }
  }

  return files;
}

function buildExportEntries(assetFiles) {
  const entries = assetFiles.map(({ filePath, exportKind, exportPrefix, extensionSuffix }) => {
    const relativePath = relative(assetsDir, filePath);
    const importPath = `./${relativePath.replace(/\\/g, "/")}`;
    const exportName = `${exportPrefix}${toExportName(relativePath)}${extensionSuffix ?? ""}`;

    return {
      exportName,
      importPath,
      line: exportKind === "component"
        ? `export { default as ${exportName} } from "${importPath}";`
        : `export const ${exportName} = require("${importPath}");`,
    };
  });

  const uniqueEntries = [];
  const usedNames = new Set();

  for (const entry of entries) {
    let candidate = entry.exportName;
    let duplicateIndex = 2;

    while (usedNames.has(candidate)) {
      candidate = `${entry.exportName}${duplicateIndex}`;
      duplicateIndex += 1;
    }

    usedNames.add(candidate);
    uniqueEntries.push({
      ...entry,
      exportName: candidate,
      line: entry.line.replace(entry.exportName, candidate),
    });
  }

  return uniqueEntries;
}

function toExportName(assetRelativePath) {
  const normalizedPath = assetRelativePath.replace(/\\/g, "/");
  const withoutExtension = normalizedPath.replace(/\.[^.]+$/, "");
  const rawTokens = withoutExtension.split(/[\/._-]+/).filter(Boolean);
  const dedupedTokens = [];

  for (const token of rawTokens) {
    if (dedupedTokens.at(-1)?.toLowerCase() === token.toLowerCase()) {
      continue;
    }

    dedupedTokens.push(token);
  }

  return dedupedTokens
    .map((token) => token.charAt(0).toUpperCase() + token.slice(1))
    .join("");
}

function formatTime() {
  return new Date().toLocaleString("zh-CN", { hour12: false });
}
